google-ID: ''

menu:
- {name: 'About', path: '.', url: 'https://www.anneouyang.com/'}
- {name: 'Blog', path: '.', url: 'https://www.anneouyang.com/blog'}

social:
- {icon: 'envelope', link: 'mailto:anne.ouyang@gmail.com'}
- {icon: 'github', link: 'https://www.github.com/anneouyang'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/anneouyang/'}
- {icon: 'twitter', link: 'https://twitter.com/anneouyang'}
- {icon: 'wechat', link: '/assets/img/wechat.jpg'}

pagination:
  next_page: 'Newer'
  previous_page: 'Older'

post_date_prefix: 'Written on'
